Check for essential binaries in Container-files
Signed-off-by: Stuart Shelton <stuart@shelton.me>

diff --git a/gentoo-base/Dockerfile.service b/gentoo-base/Dockerfile.service
--- a/gentoo-base/Dockerfile.service
+++ b/gentoo-base/Dockerfile.service
@@ -153,6 +153,21 @@ RUN set -eu ; \
             echo >&2 "FATAL: Unable to locate 'grep' binary" ; \
             exit 1 ; \
         } ; \
+    grep --help >/dev/null 2>&1 || \
+        { \
+            echo >&2 "FATAL: Unable to run 'grep' binary" ; \
+            exit 1 ; \
+        } ; \
+    command -v sed >/dev/null 2>&1 || \
+        { \
+            echo >&2 "FATAL: Unable to locate 'sed' binary" ; \
+            exit 1 ; \
+        } ; \
+    sed --help >/dev/null 2>&1 || \
+        { \
+            echo >&2 "FATAL: Unable to run 'sed' binary" ; \
+            exit 1 ; \
+        } ; \
     i="${image_name}:${service_version}" ; \
     for f in /etc/base/* ; do \
         f="$( basename "${f}" )" ; \
diff --git a/gentoo-base/Dockerfile.service-1.4 b/gentoo-base/Dockerfile.service-1.4
--- a/gentoo-base/Dockerfile.service-1.4
+++ b/gentoo-base/Dockerfile.service-1.4
@@ -166,6 +166,22 @@ RUN <<-'EOT' /bin/sh
 		echo >&2 "FATAL: Unable to locate 'grep' binary"
 		exit 1
 	fi
+	if ! grep --help >/dev/null 2>&1; then
+		echo >&2 "FATAL: Unable to run 'grep' binary"
+		set -x
+		grep --help || ldd $( command -v grep )
+		exit 1
+	fi
+	if ! command -v sed >/dev/null 2>&1; then
+		echo >&2 "FATAL: Unable to locate 'sed' binary"
+		exit 1
+	fi
+	if ! sed --help >/dev/null 2>&1; then
+		echo >&2 "FATAL: Unable to run 'sed' binary"
+		set -x
+		sed --help || ldd $( command -v sed )
+		exit 1
+	fi
 
 	i="${image_name}:${service_version}"
 	for f in /etc/base/* ; do
