Namespace image-names more clearly
Update labels to Docker standards

Parameterise stage3_flags_file and environment_file

Improve stage3 variable handling, and also extract stage3 python_* flags

Check for unexpanded template variables

Extensively revise init/base build to remove superfluous python packages

Allow entrypoint.sh to be executed interactively without errors

Fix sys-devel/gcc 'lib-only' build-flags

Fix gentoo-init.docker single stage build logic

Signed-off-by: Stuart Shelton <stuart@shelton.me>

diff --git a/gentoo-base/Dockerfile.build b/gentoo-base/Dockerfile.build
--- a/gentoo-base/Dockerfile.build
+++ b/gentoo-base/Dockerfile.build
@@ -8,6 +8,7 @@ ARG base_name="localhost/gentoo-base"
 ARG env_name="localhost/gentoo-env"
 ARG env_id=""
 
+ARG environment_file="/usr/libexec/environment.sh"
 ARG environment_filter="^(declare -x|export) (EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)="
 
 ARG ROOT="/build"
@@ -23,8 +24,9 @@ ARG PORTAGE_CONFIGROOT="${SYSROOT}"
 FROM "${base_name}:latest" AS base
 
 ARG ROOT
+ARG environment_file
 
-RUN test -s "${ROOT}"/usr/libexec/environment.sh
+RUN test -s "${ROOT}${environment_file}"
 
 
 # -----------------------------------------------------------------------------
@@ -37,6 +39,7 @@ FROM "${env_name}:latest"
 ARG env_name
 ARG env_id
 
+ARG environment_file
 ARG environment_filter
 
 ARG ROOT
@@ -47,7 +50,7 @@ ARG PORTAGE_CONFIGROOT
 # Copy the portage tree into the current stage
 #
 COPY --from=base "${ROOT}" /
-RUN test -s /usr/libexec/environment.sh
+RUN test -s "${environment_file}"
 
 # The acct-* packages don't appear to account for situations when ROOT != /,
 # and so without this we have packages registered as installed, without the
@@ -61,12 +64,12 @@ RUN test -s /usr/libexec/environment.sh
 # doesn't exist):
 RUN rm -rf /var/db/pkg/acct-* /var/empty/.keep_acct-user_sshd-0
 
-#RUN printf >&2 " * 'build' stage imported environment:\n\n%s\n\n" "$( < /usr/libexec/environment.sh )"
+#RUN printf >&2 " * 'build' stage imported environment:\n\n%s\n\n" "$( <"${environment_file}" )"
 
 LABEL maintainer="stuart@shelton.me"
-LABEL Description="Gentoo base @system image"
+LABEL description="Gentoo base @system image"
 
-LABEL envrionment_from="${env_name}:${env_id}"
+LABEL environment-from="${env_name}:${env_id}"
 
 
 # Further clean-up to minimise image size ...
@@ -75,10 +78,10 @@ LABEL envrionment_from="${env_name}:${env_id}"
 # exec-form...
 # linter ignore=SC2015,SC1091,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
-    test -s /usr/libexec/environment.sh && \
-        . /usr/libexec/environment.sh || \
+    test -s "${environment_file}" && \
+        . "${environment_file}" || \
         { \
-            echo >&2 "FATAL: Unable to source '/usr/libexec/environment.sh': ${?}" ; \
+            echo >&2 "FATAL: Unable to source '${environment_file}': ${?}" ; \
             exit 1 ; \
         } ; \
     set -u ; \
@@ -117,10 +120,10 @@ ENV PORTAGE_CONFIGROOT="${SYSROOT}"
 #
 # linter ignore=SC2015,SC1091,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
-    test -s /usr/libexec/environment.sh && \
-        . /usr/libexec/environment.sh || \
+    test -s "${environment_file}" && \
+        . "${environment_file}" || \
         { \
-            echo >&2 "FATAL: Unable to source '/usr/libexec/environment.sh': ${?}" ; \
+            echo >&2 "FATAL: Unable to source '${environment_file}': ${?}" ; \
             exit 1 ; \
         } ; \
     gcc-config 1 2>/dev/null ; \
@@ -130,18 +133,18 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
     else \
         locale-gen -k -u ; \
     fi ; \
-    printf "#FILTER: '%s'\n\n" "${environment_filter}" > /usr/libexec/environment.sh && \
+    printf "#FILTER: '%s'\n\n" "${environment_filter}" >"${environment_file}" && \
     export -p | \
             grep -- '=' | \
             grep -Ev -- "${environment_filter}" | \
             sed -r 's/\s+/ /g ; s/^(export [a-z][a-z0-9_]+=")\s+/\1/i' | \
             grep -v -e '^export [a-z_]' -e '=""$' \
-        >> /usr/libexec/environment.sh && \
-    grep >&2 -- ' ROOT=' /usr/libexec/environment.sh && { \
-            printf >&2 "Invalid 'ROOT' directive in '/usr/libexec/environment.sh':\n\n%s\n\n" "$( < /usr/libexec/environment.sh )" ; \
+        >>"${environment_file}" && \
+    grep >&2 -- ' ROOT=' "${environment_file}" && { \
+            printf >&2 "Invalid 'ROOT' directive in '${environment_file}':\n\n%s\n\n" "$( <"${environment_file}" )" ; \
             exit 1 ; \
         } || :
-#RUN printf >&2 " * 'build' stage propagated environment:\n\n%s\n\n" "$( < /usr/libexec/environment.sh )"
+#RUN printf >&2 " * 'build' stage propagated environment:\n\n%s\n\n" "$( <"${environment_file}" )"
 
 
 # Setup entrypoint script to perform a one-time copy of binary system packages
@@ -151,16 +154,17 @@ COPY entrypoint.sh.build /usr/libexec/entrypoint.sh
 RUN test -s /usr/libexec/entrypoint.sh
 
 # linter ignore=SC2015,SC1091
-RUN test -s /usr/libexec/environment.sh && \
-        . /usr/libexec/environment.sh || \
+RUN test -s "${environment_file}" && \
+        . "${environment_file}" || \
         { \
-            echo >&2 "FATAL: Unable to source '/usr/libexec/environment.sh': ${?}" ; \
+            echo >&2 "FATAL: Unable to source '${environment_file}': ${?}" ; \
             exit 1 ; \
         } ; \
     set -u ; \
     sed -i \
         -e "s/__JOBS__/${JOBS}/" \
         -e "s/__MAXLOAD__/${MAXLOAD}/" \
+        -e "s|__ENVFILE__|${environment_file}|" \
             /usr/libexec/entrypoint.sh && \
     chmod 0755 /usr/libexec/entrypoint.sh && \
     sh -n /usr/libexec/entrypoint.sh
diff --git a/gentoo-base/Dockerfile.service b/gentoo-base/Dockerfile.service
--- a/gentoo-base/Dockerfile.service
+++ b/gentoo-base/Dockerfile.service
@@ -16,6 +16,7 @@ ARG service_fs_name
 ARG timezone="GB"
 
 ARG ROOT="/service"
+ARG environment_file="/usr/libexec/environment.sh"
 ARG environment_filter="^(declare -x|export) (EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)="
 
 ARG smtp_smarthost="localhost"
@@ -29,27 +30,28 @@ ARG smtp_domain="localhost"
 FROM "localhost/${image_name}:${service_version}" AS base
 
 ARG ROOT
+ARG environment_file
 ARG environment_filter
 
 
-RUN test -s /usr/libexec/environment.sh
+RUN test -s "${environment_file}"
 
 # linter ignore=SC2015,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     set -u ; \
     mkdir -p "${ROOT}"/usr/libexec && \
-    printf "#FILTER: '%s'\n\n" "${environment_filter}" > "${ROOT}"/usr/libexec/environment.sh && \
+    printf "#FILTER: '%s'\n\n" "${environment_filter}" > "${ROOT}${environment_file}" && \
     export -p | \
             grep -- '=' | \
             grep -Ev -- "${environment_filter}" | \
             sed -r 's/\s+/ /g ; s/^(export [a-z][a-z0-9_]+=")\s+/\1/i' | \
             grep -v -e '^export [a-z_]' -e '=""$' \
-        >> "${ROOT}"/usr/libexec/environment.sh && \
-    grep >&2 -- ' ROOT=' "${ROOT}"/usr/libexec/environment.sh && { \
-            printf >&2 "Invalid 'ROOT' directive in '%s/usr/libexec/environment.sh':\n\n%s\n\n" "${ROOT%/}" "$( < "${ROOT}"/usr/libexec/environment.sh )" ; \
+        >>"${ROOT}${environment_file}" && \
+    grep >&2 -- ' ROOT=' "${ROOT}${environment_file}" && { \
+            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%/}${environment_file}" "$( <"${ROOT}${environment_file}" )" ; \
             exit 1 ; \
         } || :
-#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( < "${ROOT}"/usr/libexec/environment.sh )"
+#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( <"${ROOT}${environment_file}" )"
 
 
 # -----------------------------------------------------------------------------
@@ -72,6 +74,7 @@ ARG service_fs_name
 ARG timezone="GB"
 
 ARG ROOT
+ARG environment_file
 
 ARG smtp_smarthost
 ARG smtp_domain
@@ -83,7 +86,7 @@ ENV fs_name="${service_fs_name}"
 # Copy the installed tree into the current image
 #
 COPY --from=base "${ROOT}" /
-RUN test -s /usr/libexec/environment.sh
+RUN test -s "${environment_file}"
 
 ENV ROOT="/"
 
@@ -101,7 +104,7 @@ COPY --from=base "/usr/share/zoneinfo/${timezone}" /etc/localtime
 COPY etc/msmtprc /etc/
 
 LABEL maintainer="stuart@shelton.me"
-LABEL Description="Gentoo ${service_name}-${service_version} service"
+LABEL description="Gentoo ${service_name}-${service_version} service"
 
 # Try to get nice colours ...
 #
@@ -125,9 +128,10 @@ RUN i="${image_name}:${service_version}" ; \
         fi ; \
     done ; \
     rm -r /etc/base ; \
-    sed -e "s/__SMTP_SMARTHOST__/${smtp_smarthost}/" \
+    sed -i \
+        -e "s/__SMTP_SMARTHOST__/${smtp_smarthost}/" \
         -e "s/__DOMAIN__/${smtp_domain}/" \
-        -i /etc/msmtprc
+            /etc/msmtprc
 
 # linter ignore=SC2174
 RUN for d in 'empty' 'log' 'run'; do \
@@ -146,6 +150,9 @@ COPY entrypoint.sh.service /usr/libexec/entrypoint.sh
 COPY entrypoint.d/ /usr/libexec/entrypoint.d/
 RUN test -s /usr/libexec/entrypoint.sh && \
     chmod 0755 /usr/libexec/entrypoint.sh && \
+    sed -i \
+        -e "s|__ENVFILE__|${environment_file}|" \
+            /usr/libexec/entrypoint.sh && \
     test -x /usr/libexec/entrypoint.sh ; \
     chmod 0755 /usr/libexec/entrypoint.d/*.sh || :
 
diff --git a/gentoo-base/Dockerfile.zxtm.service b/gentoo-base/Dockerfile.zxtm.service
--- a/gentoo-base/Dockerfile.zxtm.service
+++ b/gentoo-base/Dockerfile.zxtm.service
@@ -16,6 +16,7 @@ ARG service_fs_name
 ARG timezone="GB"
 
 ARG ROOT="/service"
+ARG environment_file="/usr/libexec/environment.sh"
 ARG environment_filter="^(declare -x|export) (EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)="
 
 #ARG smtp_smarthost="localhost"
@@ -56,29 +57,30 @@ FROM "${zxtm_image_name}:${zxtm_service_version}" AS zxtm
 FROM "localhost/${image_name}:${service_version}" AS base
 
 ARG ROOT
+ARG environment_file
 ARG environment_filter
 
 ARG ZEUSHOME
 
 
-RUN test -s /usr/libexec/environment.sh
+RUN test -s "${environment_file}"
 
 # linter ignore=SC2015,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     set -u ; \
     mkdir -p "${ROOT}"/usr/libexec && \
-    printf "#FILTER: '%s'\n\n" "${environment_filter}" > "${ROOT}"/usr/libexec/environment.sh && \
+    printf "#FILTER: '%s'\n\n" "${environment_filter}" > "${ROOT}${environment_file}" && \
     export -p | \
             grep -- '=' | \
             grep -Ev -- "${environment_filter}" | \
             sed -r 's/\s+/ /g ; s/^(export [a-z][a-z0-9_]+=")\s+/\1/i' | \
             grep -v -e '^export [a-z_]' -e '=""$' \
-        >> "${ROOT}"/usr/libexec/environment.sh && \
-    grep >&2 -- ' ROOT=' "${ROOT}"/usr/libexec/environment.sh && { \
-            printf >&2 "Invalid 'ROOT' directive in '%s/usr/libexec/environment.sh':\n\n%s\n\n" "${ROOT%/}" "$( < "${ROOT}"/usr/libexec/environment.sh )" ; \
+        >>"${ROOT}${environment_file}" && \
+    grep >&2 -- ' ROOT=' "${ROOT}${environment_file}" && { \
+            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%/}${environment_file}" "$( <"${ROOT}${environment_file}" )" ; \
             exit 1 ; \
         } || :
-#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( < "${ROOT}"/usr/libexec/environment.sh )"
+#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( <"${ROOT}${environment_file}" )"
 
 # Ensure nothing from the base image screws up the ultimate combined image...
 RUN rm -rf "${ZEUSHOME}"
@@ -107,6 +109,7 @@ ARG zxtm_service_version
 ARG ZEUSHOME
 
 ARG ROOT
+ARG environment_file
 
 #ARG smtp_smarthost
 #ARG smtp_domain
@@ -122,7 +125,7 @@ ENV ZEUS_EULA="accept"
 # Copy the installed tree into the current image
 #
 COPY --from=base "${ROOT}" /
-RUN test -s /usr/libexec/environment.sh
+RUN test -s "${environment_file}"
 
 # Copy ZXTM/PS VTM into the current image
 COPY --from=zxtm /usr/local/zeus "${ZEUSHOME}/"
@@ -143,7 +146,7 @@ COPY --from=base "/usr/share/zoneinfo/${timezone}" /etc/localtime
 #COPY etc/msmtprc /etc/
 
 LABEL maintainer="stuart@shelton.me"
-LABEL Description="Pulse Secure/Ivanti ${service_name}-${service_version} service"
+LABEL description="Pulse Secure/Ivanti ${service_name}-${service_version} service"
 
 # Try to get nice colours ...
 #
@@ -204,8 +207,9 @@ RUN ln -s /proc/self/mounts /etc/mtab ; \
     ln -s var/global.cfg "${ZEUSHOME}"/admin/global.cfg && \
     ln -s var/website "${ZEUSHOME}"/admin/website ; \
     sed -i \
-        "/^zeushome=/ s|\"[^\"]*\"$|\"${ZEUSHOME}\"|" \
-        "${ZEUSHOME}/runzeus.sh"
+        -e "/^zeushome=/ s|\"[^\"]*\"$|\"${ZEUSHOME}\"|" \
+        -e "s|__ENVFILE__|${environment_file}|" \
+            "${ZEUSHOME}/runzeus.sh"
 
 # linter ignore=SC2174
 RUN for d in 'empty' 'log' 'run'; do \
