Add work-around for https://github.com/containers/podman/issues/21783
Resolve lint warnings

Signed-off-by: Stuart Shelton <stuart@shelton.me>

diff --git a/gentoo-base/Dockerfile.build b/gentoo-base/Dockerfile.build
--- a/gentoo-base/Dockerfile.build
+++ b/gentoo-base/Dockerfile.build
@@ -4,6 +4,8 @@
 #   package repo, extracted from the stage3 environment ROOT.
 
 
+# hadolint global ignore=SC2015,DL4006
+#
 ARG base_name="localhost/gentoo-base"
 ARG env_name="localhost/gentoo-env"
 ARG env_id=""
@@ -53,6 +55,7 @@ ENV SKIP_KERNEL_CHECK=1
 #
 COPY --from=base "${ROOT}" /
 RUN test -s "${environment_file}"
+RUN sh -n "${environment_file}" || { cat -n "${environment_file}" ; false ; }
 
 # The acct-* packages don't appear to account for situations when ROOT != /,
 # and so without this we have packages registered as installed, without the
@@ -66,7 +69,7 @@ RUN test -s "${environment_file}"
 # doesn't exist):
 RUN rm -rf /var/db/pkg/acct-* /var/empty/.keep_acct-user_sshd-0
 
-#RUN printf >&2 " * 'build' stage imported environment:\n\n%s\n\n" "$( <"${environment_file}" )"
+#RUN printf >&2 " * 'build' stage imported environment:\n\n%s\n\n" "$( cat "${environment_file}" )"
 
 LABEL maintainer="stuart@shelton.me"
 LABEL description="Gentoo base @system image"
@@ -78,6 +81,7 @@ LABEL environment-from="${env_name}:${env_id}"
 #
 # We can't use 'RUN [ -d ... ]' because this is interpreted as being
 # exec-form...
+#
 # linter ignore=SC2015,SC1091,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     test -s "${environment_file}" && \
@@ -117,7 +121,7 @@ ENV PORTAGE_CONFIGROOT="${SYSROOT}"
 
 # Rewrite filtered environment.sh with new values ...
 #
-# linter ignore=SC2015,SC1091,ER0001
+# linter ignore=SC2094,SC2015,SC1091,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     test -s "${environment_file}" && \
         . "${environment_file}" || \
@@ -142,10 +146,10 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
             grep -v -e '^export [a-z_]' -e '=""$' \
         >>"${environment_file}" && \
     grep >&2 -- ' ROOT=' "${environment_file}" && { \
-            printf >&2 "Invalid 'ROOT' directive in '${environment_file}':\n\n%s\n\n" "$( <"${environment_file}" )" ; \
+            printf >&2 "Invalid 'ROOT' directive in '${environment_file}':\n\n%s\n\n" "$( cat "${environment_file}" )" ; \
             exit 1 ; \
         } || :
-#RUN printf >&2 " * 'build' stage propagated environment:\n\n%s\n\n" "$( <"${environment_file}" )"
+#RUN printf >&2 " * 'build' stage propagated environment:\n\n%s\n\n" "$( cat "${environment_file}" )"
 
 
 # Setup entrypoint script to perform a one-time copy of binary system packages
@@ -179,4 +183,5 @@ RUN test ! -x /usr/sbin/locale-gen || /usr/sbin/locale-gen
 ENTRYPOINT ["/usr/libexec/entrypoint.sh"]
 CMD ["app-shells/bash"]
 
+# linter ignore=ED0004
 # vi: set syntax=dockerfile expandtab nowrap colorcolumn=80:
diff --git a/gentoo-base/Dockerfile.service b/gentoo-base/Dockerfile.service
--- a/gentoo-base/Dockerfile.service
+++ b/gentoo-base/Dockerfile.service
@@ -2,6 +2,8 @@
 # service:
 #   Extract a ROOT-installed service.
 
+# hadolint global ignore=DL4006,DL3025,SC3040,SC2174,SC2015,SC2012
+#
 ARG image_name
 ARG service_name
 ARG service_name_short
@@ -40,7 +42,7 @@ ARG environment_filter
 
 RUN test -s "${environment_file}"
 
-# linter ignore=SC2015,ER0001
+# linter ignore=SC2094,SC2015,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     set -u ; \
     mkdir -p "${ROOT}"/usr/libexec && \
@@ -52,13 +54,13 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
             grep -v -e '^export [a-z_]' -e '=""$' \
         >>"${ROOT}${environment_file}" && \
     grep >&2 -- ' ROOT=' "${ROOT}${environment_file}" && { \
-            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%"/"}${environment_file}" "$( <"${ROOT}${environment_file}" )" ; \
+            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%"/"}${environment_file}" "$( cat "${ROOT}${environment_file}" )" ; \
             exit 1 ; \
         } || : ; \
     if [ -s /builddeps.txt ] && ! [ -s "${ROOT}/builddeps.txt" ]; then \
         mv /builddeps.txt "${ROOT}/builddeps.txt" ; \
     fi
-#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( <"${ROOT}${environment_file}" )"
+#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( cat "${ROOT}${environment_file}" )"
 
 
 # -----------------------------------------------------------------------------
@@ -125,9 +127,12 @@ ENV ROOT="/"
 
 #RUN cat "/var/db/pkg/${service_name}-${service_version}/CONTENTS"
 
-# linter ignore=ER0001
-RUN i="${image_name}:${service_version}" ; \
-    for f in /etc/base/*; do \
+RUN test -x /bin/busybox
+
+# linter ignore=SC2050,SC2012,ER0001
+RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    i="${image_name}:${service_version}" ; \
+    for f in /etc/base/* ; do \
         f="$( basename "${f}" )" ; \
         if ! [ -s "/etc/${f}" ]; then \
             echo "INFO:  Adding new file '${f}' from base image '${i}' ..." ; \
@@ -150,21 +155,21 @@ RUN i="${image_name}:${service_version}" ; \
             /etc/msmtprc ; \
     if [ -d "${ROOT}"/usr/lib/gcc ]; then \
         if ! [ -d "${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" ]; then \
-            echo "WARN:  Directory '${ROOT}/usr/lib/gcc' exists but '${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}' doesn't exist" ; \
+            echo "WARN:  Directory '${ROOT}/usr/lib/gcc' exists but" \
+                "'${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}'" \
+                "doesn't" ; \
             ls -1AF "${ROOT}/usr/lib/gcc" | sed 's/^/DEBUG: /' ; \
-        else \
-            if ! grep -Fqm 1 '/gcc/' /etc/ld.so.conf; then \
-                find "/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" \
-                        -mindepth 1 \
-                        -maxdepth 1 \
-                        -type d \
-                    -print0 | xargs -0rn 1 >> /etc/ld.so.conf ; \
-                ldconfig ; \
-            fi ; \
+        elif ! grep -Fqm 1 '/gcc/' /etc/ld.so.conf; then \
+            find "/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" \
+                    -mindepth 1 \
+                    -maxdepth 1 \
+                    -type d \
+                -print0 | xargs -0rn 1 >> /etc/ld.so.conf ; \
+            ldconfig ; \
         fi ; \
     fi
 
-# linter ignore=SC2174
+# linter ignore=SC2174,SC2050
 RUN for d in 'empty' 'log' 'run' 'lock'; do \
         if test -e "/var/${d}" && { test -L "/var/${d}" || ! test -d "/var/${d}"; }; then \
             rm "/var/${d}" ; \
@@ -181,14 +186,13 @@ RUN for d in 'empty' 'log' 'run' 'lock'; do \
             usr/lib64/pkgconfig usr/share/awk usr/share/udhcpc \
             var/cache/edb var/db/Makefile var/lib/gentoo ; \
     do \
-        [ -e "${d}" ] && rm -rf "/${d}" ; \
+        [ -e "${d}" ] && rm -rf "/${d:?}" ; \
     done ; \
     if [ "${service_name}" != 'mail-filter/spamassassin-update' ]; then \
-        d='usr/include' ; \
-        [ -e "${d}" ] && rm -rf "/${d}" ; \
+        [ -e usr/include ] && rm -rf /usr/include ; \
     fi ; \
     if [ -d usr/share/gcc-data ]; then \
-        rm -rf "/usr/share/gcc-data/*/*/man" "/usr/share/gcc-data/*/*/info" ; \
+        rm -rf /usr/share/gcc-data/*/*/man /usr/share/gcc-data/*/*/info ; \
     fi
 
 # Setup entrypoint script to perform a one-time copy of binary system packages
@@ -204,14 +208,18 @@ RUN test -s /usr/libexec/entrypoint.sh && \
     test -x /usr/libexec/entrypoint.sh ; \
     chmod 0755 /usr/libexec/entrypoint.d/*.sh || :
 
-RUN ldconfig ; \
+# linter ignore=ER0001,SC2015
+RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    ldconfig ; \
     find / -xdev -type f -executable -not -name '*.sh' | while read -r x; do \
         ldd "${x}" 2>&1 | \
             sed "s|^|${x}: |" | \
             grep 'not found' && exit 1 || : ; \
     done
 
-RUN echo "${service_cmd}" ; \
+# linter ignore=ER0001
+RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    echo "${service_cmd}" ; \
     test -x "${service_cmd}" && \
     if ! [ "$( \
         head -n 1 "${service_cmd}" | \
@@ -245,6 +253,8 @@ RUN test ! -x /usr/bin/mandb || \
     nice mandb --create
 
 # Run eselect for dependent components...
+#
+# hadolint ignore=SC3028
 RUN if [ -x /usr/bin/eselect ]; then \
         if [ -s /usr/share/eselect/modules/python.eselect ]; then \
             if [ $(( ${EUID:-"$( id -u )"} )) -eq 0 ]; then \
@@ -270,13 +280,14 @@ RUN if [ -x /usr/sbin/prelink ]; then \
         /usr/sbin/prelink -p ; \
     fi
 
-EXPOSE "${service_ports}"
+EXPOSE ${service_ports}
 
 # linter ignore=EW0001
 WORKDIR "${service_cwd}"
 
 USER "${service_user}:${service_group}"
 
+# hadolint ignore=SC3028
 RUN if [ -x /usr/bin/eselect ]; then \
         if [ -s /usr/share/eselect/modules/java-vm.eselect ]; then \
             echo "Setting Java VM as '${service_user:-"root"}' ..." ; \
@@ -293,7 +304,9 @@ VOLUME ["/srv/${service_name_short}","/var/db/pkg"]
 ENTRYPOINT ["/usr/libexec/entrypoint.sh"]
 
 # Must be in shell-form to interpolate ARG/ENV values...
+#
 # linter ignore=EJ0002
 CMD "${service_cmd}"
 
+# linter ignore=ED0004
 # vi: set syntax=dockerfile expandtab sw=4 ts=4 nowrap colorcolumn=80:
diff --git a/gentoo-base/Dockerfile.service.zxtm b/gentoo-base/Dockerfile.service.zxtm
--- a/gentoo-base/Dockerfile.service.zxtm
+++ b/gentoo-base/Dockerfile.service.zxtm
@@ -2,6 +2,8 @@
 # service:
 #   Extract a ROOT-installed service, and overlay PulseSecure VTM (Zeus ZXTM).
 
+# hadolint global ignore=DL4006,DL3059,DL3025,SC3040,SC2174,SC2015,SC2012
+#
 ARG image_name
 ARG service_name
 ARG service_name_short
@@ -21,8 +23,8 @@ ARG ROOT="/service"
 ARG environment_file="/usr/libexec/environment.sh"
 ARG environment_filter="^(declare -x|export) (EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)="
 
-#ARG smtp_smarthost="localhost"
-#ARG smtp_domain="localhost"
+ARG smtp_smarthost="localhost"
+ARG smtp_domain="localhost"
 
 ARG CHOST="x86_64-pc-linux-gnu"
 
@@ -70,11 +72,13 @@ ARG ZEUSHOME
 RUN test -s "${environment_file}"
 
 # Ensure nothing from the base image screws up the ultimate combined image...
+#
+# linter ignore=SC2050
 RUN if ! [ "${ZEUSHOME}" = '/usr/local/zeus' ]; then \
         rm -rf "${ZEUSHOME}" ; \
     fi
 
-# linter ignore=SC2015,ER0001
+# linter ignore=SC2094,SC2015,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     set -u ; \
     mkdir -p "${ROOT}"/usr/libexec && \
@@ -86,13 +90,13 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
             grep -v -e '^export [a-z_]' -e '=""$' \
         >>"${ROOT}${environment_file}" && \
     grep >&2 -- ' ROOT=' "${ROOT}${environment_file}" && { \
-            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%"/"}${environment_file}" "$( <"${ROOT}${environment_file}" )" ; \
+            printf >&2 "Invalid 'ROOT' directive in '%s':\n\n%s\n\n" "${ROOT%"/"}${environment_file}" "$( cat "${ROOT}${environment_file}" )" ; \
             exit 1 ; \
         } || : ; \
     if [ -s /builddeps.txt ] && ! [ -s "${ROOT}/builddeps.txt" ]; then \
         mv /builddeps.txt "${ROOT}/builddeps.txt" ; \
     fi
-#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( <"${ROOT}${environment_file}" )"
+#RUN printf >&2 " * 'service' stage propagated environment:\n\n%s\n\n" "$( cat "${ROOT}${environment_file}" )"
 
 
 # -----------------------------------------------------------------------------
@@ -101,7 +105,7 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
 #
 FROM scratch
 
-#ARG image_name
+ARG image_name
 ARG service_name
 ARG service_name_short
 ARG service_version
@@ -122,8 +126,8 @@ ARG ZEUSHOME
 ARG ROOT
 ARG environment_file
 
-#ARG smtp_smarthost
-#ARG smtp_domain
+ARG smtp_smarthost
+ARG smtp_domain
 
 ARG CHOST
 
@@ -171,9 +175,12 @@ ENV ROOT="/"
 
 #RUN cat "/var/db/pkg/${service_name}-${service_version}/CONTENTS"
 
-# linter ignore=ER0001
-RUN i="${image_name}:${service_version}" ; \
-    for f in /etc/base/*; do \
+RUN test -x /bin/busybox
+
+# linter ignore=SC2050,SC2012,ER0001
+RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    i="${image_name}:${service_version}" ; \
+    for f in /etc/base/* ; do \
         f="$( basename "${f}" )" ; \
         if ! [ -s "/etc/${f}" ]; then \
             echo "INFO:  Adding new file '${f}' from base image '${i}' ..." ; \
@@ -196,17 +203,17 @@ RUN i="${image_name}:${service_version}" ; \
             /etc/msmtprc ; \
     if [ -d "${ROOT}"/usr/lib/gcc ]; then \
         if ! [ -d "${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" ]; then \
-            echo "WARN:  Directory '${ROOT}/usr/lib/gcc' exists but '${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}' doesn't exist" ; \
+            echo "WARN:  Directory '${ROOT}/usr/lib/gcc' exists but" \
+                "'${ROOT}/usr/lib/gcc/${CHOST:-"__chost_not_set__"}'" \
+                "doesn't" ; \
             ls -1AF "${ROOT}/usr/lib/gcc" | sed 's/^/DEBUG: /' ; \
-        else \
-            if ! grep -Fqm 1 '/gcc/' /etc/ld.so.conf; then \
-                find "/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" \
-                        -mindepth 1 \
-                        -maxdepth 1 \
-                        -type d \
-                    -print0 | xargs -0rn 1 >> /etc/ld.so.conf ; \
-                ldconfig ; \
-            fi ; \
+        elif ! grep -Fqm 1 '/gcc/' /etc/ld.so.conf; then \
+            find "/usr/lib/gcc/${CHOST:-"__chost_not_set__"}" \
+                    -mindepth 1 \
+                    -maxdepth 1 \
+                    -type d \
+                -print0 | xargs -0rn 1 >> /etc/ld.so.conf ; \
+            ldconfig ; \
         fi ; \
     fi
 
@@ -246,7 +253,7 @@ RUN ln -s /proc/self/mounts /etc/mtab ; \
         -e "/^zeushome=/ s|\"[^\"]*\"$|\"${ZEUSHOME}\"|" \
         -e "s|__ENVFILE__|${environment_file}|"
 
-# linter ignore=SC2174
+# linter ignore=SC2174,SC2050
 RUN for d in 'empty' 'log' 'run' 'lock'; do \
         if test -e "/var/${d}" && { test -L "/var/${d}" || ! test -d "/var/${d}"; }; then \
             rm "/var/${d}" ; \
@@ -263,14 +270,13 @@ RUN for d in 'empty' 'log' 'run' 'lock'; do \
             usr/lib64/pkgconfig usr/share/awk usr/share/udhcpc \
             var/cache/edb var/db/Makefile var/lib/gentoo ; \
     do \
-        [ -e "${d}" ] && rm -rf "/${d}" ; \
+        [ -e "${d}" ] && rm -rf "/${d:?}" ; \
     done ; \
     if [ "${service_name}" != 'mail-filter/spamassassin-update' ]; then \
-        d='usr/include' ; \
-        [ -e "${d}" ] && rm -rf "/${d}" ; \
+        [ -e usr/include ] && rm -rf /usr/include ; \
     fi ; \
     if [ -d usr/share/gcc-data ]; then \
-        rm -rf "/usr/share/gcc-data/*/*/man" "/usr/share/gcc-data/*/*/info" ; \
+        rm -rf /usr/share/gcc-data/*/*/man /usr/share/gcc-data/*/*/info ; \
     fi
 
 #RUN eselect iptables list
@@ -287,15 +293,19 @@ RUN for d in 'empty' 'log' 'run' 'lock'; do \
 #            /usr/libexec/entrypoint.sh && \
 #    test -x /usr/libexec/entrypoint.sh ; \
 #    chmod 0755 /usr/libexec/entrypoint.d/*.sh || :
-#
-#RUN ldconfig ; \
+
+# linter ignore=ER0001,SC2015
+#RUN { set -o pipefail 2>/dev/null || true ; } ; \
+#    ldconfig ; \
 #    find / -xdev -type f -executable -not -name '*.sh' | while read -r x; do \
 #        ldd "${x}" 2>&1 | \
 #            sed "s|^|${x}: |" | \
 #            grep 'not found' && exit 1 || : ; \
 #    done
-#
-#RUN echo "${service_cmd}" ; \
+
+# linter ignore=ER0001
+#RUN { set -o pipefail 2>/dev/null || true ; } ; \
+#    echo "${service_cmd}" ; \
 #    test -x "${service_cmd}" && \
 #    if ! [ "$( \
 #        head -n 1 "${service_cmd}" | \
@@ -370,6 +380,8 @@ RUN test ! -x /usr/bin/mandb || \
     nice mandb --create
 
 # Run eselect for dependent components...
+#
+# hadolint ignore=SC3028
 #RUN if [ -x /usr/bin/eselect ]; then \
 #        if [ -s /usr/share/eselect/modules/python.eselect ]; then \
 #            if [ $(( ${EUID:-"$( id -u )"} )) -eq 0 ]; then \
@@ -395,13 +407,14 @@ RUN if [ -x /usr/sbin/prelink ]; then \
         /usr/sbin/prelink -p ; \
     fi
 
-EXPOSE "${service_ports}"
+EXPOSE ${service_ports}
 
 # linter ignore=EW0001
 WORKDIR "${service_cwd}"
 
 USER "${service_user}:${service_group}"
 
+# hadolint ignore=SC3028
 #RUN if [ -x /usr/bin/eselect ]; then \
 #        if [ -s /usr/share/eselect/modules/java-vm.eselect ]; then \
 #            echo "Setting Java VM as '${service_user:-"root"}' ..." ; \
@@ -418,6 +431,7 @@ VOLUME ["/srv/${service_name_short}","/var/db/pkg"]
 
 #ENTRYPOINT ["/usr/libexec/entrypoint.sh"]
 # Must be in shell-form to interpolate ARG/ENV values...
+#
 # linter ignore=EJ0002
 ENTRYPOINT "${ZEUSHOME}/runzeus.sh"
 
@@ -425,4 +439,5 @@ ENTRYPOINT "${ZEUSHOME}/runzeus.sh"
 # linter ignore=EJ0002
 #CMD "${service_cmd}"
 
+# linter ignore=ED0004
 # vi: set syntax=dockerfile expandtab sw=4 ts=4 nowrap colorcolumn=80:
