Add sanity-check to all (non-'init') Container-files to abort if 'grep' has inadvertently been removed from prior images
Update vim modeline

Signed-off-by: Stuart Shelton <stuart@shelton.me>

diff --git a/gentoo-base/Dockerfile.build b/gentoo-base/Dockerfile.build
--- a/gentoo-base/Dockerfile.build
+++ b/gentoo-base/Dockerfile.build
@@ -129,6 +129,11 @@ RUN { set -o pipefail 2>/dev/null || true ; } ; \
             echo >&2 "FATAL: Unable to source '${environment_file}': ${?}" ; \
             exit 1 ; \
         } ; \
+    command -v grep || \
+        { \
+            echo >&2 "FATAL: Unable to locate 'grep' binary" ; \
+            exit 1 ; \
+        } ; \
     gcc-config 1 2>/dev/null ; \
     test -s /etc/profile && . /etc/profile ; \
     if [ -x /usr/sbin/locale-gen ]; then \
@@ -184,4 +189,4 @@ ENTRYPOINT ["/usr/libexec/entrypoint.sh"]
 CMD ["app-shells/bash"]
 
 # linter ignore=ED0004
-# vi: set syntax=dockerfile expandtab nowrap colorcolumn=80:
+# vi: set colorcolumn=80 expandtab shiftwidth=4 syntax=dockerfile tabstop=4 nowrap:
diff --git a/gentoo-base/Dockerfile.service b/gentoo-base/Dockerfile.service
--- a/gentoo-base/Dockerfile.service
+++ b/gentoo-base/Dockerfile.service
@@ -45,6 +45,11 @@ RUN test -s "${environment_file}"
 # linter ignore=SC2094,SC2015,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
     set -u ; \
+    command -v grep || \
+        { \
+            echo >&2 "FATAL: Unable to locate 'grep' binary" ; \
+            exit 1 ; \
+        } ; \
     mkdir -p "${ROOT}"/usr/libexec && \
     printf "#FILTER: '%s'\n\n" "${environment_filter}" > "${ROOT}${environment_file}" && \
     export -p | \
@@ -131,6 +136,11 @@ RUN test -x /bin/busybox
 
 # linter ignore=SC2050,SC2012,ER0001
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    command -v grep || \
+        { \
+            echo >&2 "FATAL: Unable to locate 'grep' binary" ; \
+            exit 1 ; \
+        } ; \
     i="${image_name}:${service_version}" ; \
     for f in /etc/base/* ; do \
         f="$( basename "${f}" )" ; \
@@ -309,4 +319,4 @@ ENTRYPOINT ["/usr/libexec/entrypoint.sh"]
 CMD "${service_cmd}"
 
 # linter ignore=ED0004
-# vi: set syntax=dockerfile expandtab sw=4 ts=4 nowrap colorcolumn=80:
+# vi: set colorcolumn=80 expandtab shiftwidth=4 syntax=dockerfile tabstop=4 nowrap:
diff --git a/gentoo-base/Dockerfile.stage3 b/gentoo-base/Dockerfile.stage3
--- a/gentoo-base/Dockerfile.stage3
+++ b/gentoo-base/Dockerfile.stage3
@@ -47,6 +47,11 @@ ARG new_root_name
 #
 # linter ignore=ER0001,SC2028,SC2046
 RUN { set -o pipefail 2>/dev/null || true ; } ; \
+    command -v grep || \
+        { \
+            echo >&2 "FATAL: Unable to locate 'grep' binary" ; \
+            exit 1 ; \
+        } ; \
     pe="$( \
         find /var/db/pkg/dev-lang/ \
                 -mindepth 1 \
@@ -191,4 +196,4 @@ COPY --from=stage3 "/${new_root_name}" /
 RUN test ! -e /var/db/repos || rm -r /var/db/repos
 
 # linter ignore=ED0004
-# vi: set syntax=dockerfile colorcolumn=80 expandtab nowrap shiftwidth=4 tabstop=4:
+# vi: set colorcolumn=80 expandtab shiftwidth=4 syntax=dockerfile tabstop=4 nowrap:
